
# Application class
application: Finwo\RestProxy

# Note of the authors
authors:
  - Robin Bron <robin@finwo.nl>

routes:
  rest_proxy:
    type: rest
    path: ^\/(?<resource>[a-z\/]+)(\.(?<format>[a-z]+))?$
    method: GET
    prefix: /rest
    controller: Finwo\RestProxy:Rest:get
    defaults:
      format: json